Homework 5
================

## Problem 1

Did not include as it isn’t graded.

## Problem 2

### Import CSV

``` r
hom_df =
  read_csv("./data/homicide-data.csv")
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Raw Data Description

``` r
skimr::skim(hom_df)
```

The homicide data contains 52179 observations and 12 variables. For each
reported case of homicide, the dataset provides victim’s name, race,
age, sex, location (city, state, latitude, and longitude), and
disposition.

### Number of Homicides and Unsolved Cases in Each City, State

``` r
hom_df = hom_df %>% 
  mutate(city_state = str_c(city, state, sep = ", "))

n_homicide = hom_df %>% 
  group_by(city_state) %>% 
  summarize(n_homicide = n())

n_unsolved = hom_df %>% 
  filter(disposition %in% c("Closed without arrest", "Open/No arrest")) %>% 
  group_by(city_state) %>% 
  summarize(n_unsolved = n())

summ = left_join(n_homicide, n_unsolved, by = "city_state") 
knitr::kable(summ)
```

| city_state         | n_homicide | n_unsolved |
|:-------------------|-----------:|-----------:|
| Albuquerque, NM    |        378 |        146 |
| Atlanta, GA        |        973 |        373 |
| Baltimore, MD      |       2827 |       1825 |
| Baton Rouge, LA    |        424 |        196 |
| Birmingham, AL     |        800 |        347 |
| Boston, MA         |        614 |        310 |
| Buffalo, NY        |        521 |        319 |
| Charlotte, NC      |        687 |        206 |
| Chicago, IL        |       5535 |       4073 |
| Cincinnati, OH     |        694 |        309 |
| Columbus, OH       |       1084 |        575 |
| Dallas, TX         |       1567 |        754 |
| Denver, CO         |        312 |        169 |
| Detroit, MI        |       2519 |       1482 |
| Durham, NC         |        276 |        101 |
| Fort Worth, TX     |        549 |        255 |
| Fresno, CA         |        487 |        169 |
| Houston, TX        |       2942 |       1493 |
| Indianapolis, IN   |       1322 |        594 |
| Jacksonville, FL   |       1168 |        597 |
| Kansas City, MO    |       1190 |        486 |
| Las Vegas, NV      |       1381 |        572 |
| Long Beach, CA     |        378 |        156 |
| Los Angeles, CA    |       2257 |       1106 |
| Louisville, KY     |        576 |        261 |
| Memphis, TN        |       1514 |        483 |
| Miami, FL          |        744 |        450 |
| Milwaukee, wI      |       1115 |        403 |
| Minneapolis, MN    |        366 |        187 |
| Nashville, TN      |        767 |        278 |
| New Orleans, LA    |       1434 |        930 |
| New York, NY       |        627 |        243 |
| Oakland, CA        |        947 |        508 |
| Oklahoma City, OK  |        672 |        326 |
| Omaha, NE          |        409 |        169 |
| Philadelphia, PA   |       3037 |       1360 |
| Phoenix, AZ        |        914 |        504 |
| Pittsburgh, PA     |        631 |        337 |
| Richmond, VA       |        429 |        113 |
| Sacramento, CA     |        376 |        139 |
| San Antonio, TX    |        833 |        357 |
| San Bernardino, CA |        275 |        170 |
| San Diego, CA      |        461 |        175 |
| San Francisco, CA  |        663 |        336 |
| Savannah, GA       |        246 |        115 |
| St. Louis, MO      |       1677 |        905 |
| Stockton, CA       |        444 |        266 |
| Tampa, FL          |        208 |         95 |
| Tulsa, AL          |          1 |         NA |
| Tulsa, OK          |        583 |        193 |
| Washington, DC     |       1345 |        589 |

### Baltimore, MD: Proportion of Unsolved Homicide Cases

``` r
MD_unsolved = summ %>% 
  filter(city_state == "Baltimore, MD")

MD_prop = prop.test(MD_unsolved %>%  pull(n_unsolved), MD_unsolved %>% pull(n_homicide)) %>% 
  broom::tidy()

MD_prop
```

    ## # A tibble: 1 × 8
    ##   estimate statistic  p.value parameter conf.low conf.high method        alter…¹
    ##      <dbl>     <dbl>    <dbl>     <int>    <dbl>     <dbl> <chr>         <chr>  
    ## 1    0.646      239. 6.46e-54         1    0.628     0.663 1-sample pro… two.si…
    ## # … with abbreviated variable name ¹​alternative

64.6% (95% CI: 62.8%, 66.3%) of reported homicides in Baltimore, MD are
unsolved cases.
